In [13]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                    "P106", "P107", "P108", "P109", "P110"],

     "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

     "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
              "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
              "Hyderabad", "Karimnagar"],

     "Surgery_Type": [
         "Cholecystectomy", "CABG", "Appendectomy",
         "Hernia Repair", "Knee Replacement", "PTCA",
         "Appendectomy", "Cholecystectomy",
         "Hernia Repair", "Knee Replacement"
     ],

     "Operation_Duration_Min": [90, 240, 75, 110, 180,
                                150, 70, 95, 120, 200],

     "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                             4, 1, 2, 3, 6],

     "Admission_Type": [
         "Planned", "Emergency", "Emergency", "Planned",
         "Planned", "Emergency", "Emergency", "Planned",
         "Planned", "Planned"
     ]
 }

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [14]:
#describe()   # statical suummary
#age ka overall summary chahiye

df["Age"].describe()

count    10.000000
mean     50.600000
std      14.276632
min      29.000000
25%      42.000000
50%      49.500000
75%      60.250000
max      73.000000
Name: Age, dtype: float64

In [15]:
df["Operation_Duration_Min"].describe()

count     10.000000
mean     133.000000
std       57.503623
min       70.000000
25%       91.250000
50%      115.000000
75%      172.500000
max      240.000000
Name: Operation_Duration_Min, dtype: float64

In [16]:
df["Length_of_Stay_Days"].describe()

count    10.000000
mean      3.400000
std       2.065591
min       1.000000
25%       2.000000
50%       3.000000
75%       4.750000
max       7.000000
Name: Length_of_Stay_Days, dtype: float64

In [17]:
df[["Age","Length_of_Stay_Days","Operation_Duration_Min"]].describe()

             Age  Length_of_Stay_Days  Operation_Duration_Min
count  10.000000            10.000000               10.000000
mean   50.600000             3.400000              133.000000
std    14.276632             2.065591               57.503623
min    29.000000             1.000000               70.000000
25%    42.000000             2.000000               91.250000
50%    49.500000             3.000000              115.000000
75%    60.250000             4.750000              172.500000
max    73.000000             7.000000              240.000000

numerical data ki quick report card  -- describe()

In [18]:
import pandas as pd

data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

df = pd.DataFrame(data)

df

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [19]:
# har department mien kitne patient hain

df.groupby("Department")

In [20]:
df.groupby("Department")["Patient_ID"].size()

Department
Cardiology    4
Neurology     3
Orthopedic    3
Name: Patient_ID, dtype: int64

In [21]:
df.groupby("Department")["Patient_ID"].count()

Department
Cardiology    4
Neurology     3
Orthopedic    3
Name: Patient_ID, dtype: int64

main formuka
df.groupby("Group_Column")["Value_column"].functioon()

In [22]:
#har departments me average treatment cost kkitni hai
df.groupby("Department")["Treatment_Cost"].mean()

Department
Cardiology    57500.0
Neurology     35000.0
Orthopedic    55000.0
Name: Treatment_Cost, dtype: float64

In [23]:
#har department ko total treatment cost kitna hai

#gp --- >dept, select -- treatment

In [24]:
df.groupby("Department")["Treatment_Cost"].sum()

Department
Cardiology    230000
Neurology     105000
Orthopedic    165000
Name: Treatment_Cost, dtype: int64

1. Maximum Treatment Cost in each Department

In [25]:
df.groupby("Department")["Treatment_Cost"].max()

Department
Cardiology    65000
Neurology     40000
Orthopedic    70000
Name: Treatment_Cost, dtype: int64

2. Patient_ID having Maximum Treatment Cost

In [26]:
df.loc[df.groupby("Department")["Treatment_Cost"].idxmax(),["Department", "Patient_ID", "Treatment_Cost"]]

   Department  Patient_ID  Treatment_Cost
8  Cardiology         109           65000
7   Neurology         108           40000
6  Orthopedic         107           70000

In [27]:
df.groupby("Department").agg({
    "Patient_ID": "count",
    "Age": "mean",
    "Treatment_Cost": "sum",
    "Hospital_Stay": "mean"
})

            Patient_ID        Age  Treatment_Cost  Hospital_Stay
Department
Cardiology           4  35.750000          230000       5.500000
Neurology            3  45.000000          105000       2.666667
Orthopedic           3  51.666667          165000       5.000000

In [28]:
# 3. Minimum Treatment Cost
df.groupby("Department")["Treatment_Cost"].min()

Department
Cardiology    50000
Neurology     30000
Orthopedic    45000
Name: Treatment_Cost, dtype: int64

In [29]:
# Patient_ID having Minimum Treatment Cost
df.loc[df.groupby("Department")["Treatment_Cost"].idxmin(),
       ["Department", "Patient_ID", "Treatment_Cost"]]

   Department  Patient_ID  Treatment_Cost
0  Cardiology         101           50000
4   Neurology         105           30000
3  Orthopedic         104           45000

Maximum value → max()
Maximum value's row → idxmax()

Minimum value → min()
Minimum value's row → idxmin()

In [30]:
# 5. Average Treatment Cost
df.groupby("Department")["Treatment_Cost"].mean()

Department
Cardiology    57500.0
Neurology     35000.0
Orthopedic    55000.0
Name: Treatment_Cost, dtype: float64

In [31]:
# 6. Total Treatment Cost
df.groupby("Department")["Treatment_Cost"].sum()

Department
Cardiology    230000
Neurology     105000
Orthopedic    165000
Name: Treatment_Cost, dtype: int64

In [32]:
df.groupby("Department").size()

Department
Cardiology    4
Neurology     3
Orthopedic    3
dtype: int64

In [33]:
#Avg hospital stay
df.groupby("Department")["Hospital_Stay"].mean()

Department
Cardiology    5.500000
Neurology     2.666667
Orthopedic    5.000000
Name: Hospital_Stay, dtype: float64

In [34]:
# Patient with Maximum Hospital Stay
df.loc[df.groupby("Department")["Hospital_Stay"].idxmax(),
       ["Department", "Patient_ID", "Hospital_Stay"]]

   Department  Patient_ID  Hospital_Stay
2  Cardiology         103              6
1   Neurology         102              3
6  Orthopedic         107              7

In [35]:
# 10. City-wise Maximum Treatment Cost Patient
df.loc[df.groupby("City")["Treatment_Cost"].idxmax(),
       ["City","Patient_ID","Treatment_Cost"]]

     City  Patient_ID  Treatment_Cost
6  Mumbai         107           70000
8  Nagpur         109           65000
7    Pune         108           40000

In [36]:
df.groupby("City")["Age"].mean()

City
Mumbai    51.666667
Nagpur    35.750000
Pune      45.000000
Name: Age, dtype: float64

In [37]:
df.groupby("City")["Treatment_Cost"].sum()

City
Mumbai    165000
Nagpur    230000
Pune      105000
Name: Treatment_Cost, dtype: int64

In [38]:
# Oldest Patient in Each Department
df.loc[df.groupby("Department")["Age"].idxmax(),
       ["Department", "Patient_ID", "Age"]]

   Department  Patient_ID  Age
8  Cardiology         109   55
4   Neurology         105   50
6  Orthopedic         107   65

In [39]:
# 14. Minimum Hospital Stay Patient
df.loc[df.groupby("Department")["Hospital_Stay"].min(),
       ["Department", "Patient_ID", "Hospital_Stay"]]

   Department  Patient_ID  Hospital_Stay
5  Cardiology         106              5
2  Cardiology         103              6
4   Neurology         105              2

In [40]:
report = df.groupby("Department").agg(
    Total_Patients=("Patient_ID", "count"),
    Average_Treatment_Cost=("Treatment_Cost", "mean"),
    Maximum_Treatment_Cost=("Treatment_Cost", "max")
)

print(report)

            Total_Patients  Average_Treatment_Cost  Maximum_Treatment_Cost
Department
Cardiology               4                 57500.0                   65000
Neurology                3                 35000.0                   40000
Orthopedic               3                 55000.0                   70000

In [41]:
report = df.groupby("Department").agg(
    Patient_Count=("Patient_ID", "count"),
    Average_Age=("Age", "mean"),
    Total_Treatment_Cost=("Treatment_Cost", "sum"),
    Maximum_Treatment_Cost=("Treatment_Cost", "max"),
    Average_Hospital_Stay=("Hospital_Stay", "mean")
)

print(report)

            Patient_Count  Average_Age  Total_Treatment_Cost  \
Department
Cardiology              4    35.750000                230000
Neurology               3    45.000000                105000
Orthopedic              3    51.666667                165000

            Maximum_Treatment_Cost  Average_Hospital_Stay
Department
Cardiology                   65000               5.500000
Neurology                    40000               2.666667
Orthopedic                   70000               5.000000

In [42]:
df.groupby("Department").agg( {
    "Patient_ID" : "count" ,
    "Age" : "mean",
    "Treatment_Cost" : ("sum","mean"),
    "Hospital_Stay" : "mean"
}
)

           Patient_ID        Age Treatment_Cost          Hospital_Stay
                count       mean            sum     mean          mean
Department
Cardiology          4  35.750000         230000  57500.0      5.500000
Neurology           3  45.000000         105000  35000.0      2.666667
Orthopedic          3  51.666667         165000  55000.0      5.000000