In [1]:
import pandas as pd

In [2]:
# df_test={
#     "Patient_ID":["a1","a2","a3","c1","c2"],
#     "Age":[18,19,30,23,25],
#     "Surgery_Type":["Heart","Leg","Neck","Hand","Ear"]
# }

# df=pd.DataFrame(df_test)

# df

In [3]:
import pandas as pd

data = {
"Patient_ID": ["P101", "P102", "P103", "P104", "P105", "P106", "P107", "P108", "P109", "P110"],

"Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],
"City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
"Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
"Hyderabad", "Karimnagar"],

"Surgery_Type": [
"Cholecystectomy", "CABG", "Appendectomy",
"Hernia Repair", "Knee Replacement", "PTCA",
"Appendectomy", "Cholecystectomy",
"Hernia Repair", "Knee Replacement"
],

"Operation_Duration_Min": [90, 240, 75, 110, 180,150, 70, 95, 120, 200],

"Length_of_Stay_Days": [2, 7, 1, 3, 5,
4, 1, 2, 3, 6],

"Admission_Type": [
"Planned", "Emergency", "Emergency", "Planned",
"Planned", "Emergency", "Emergency", "Planned",
"Planned", "Planned"
]
}

df = pd.DataFrame(data)

df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [4]:
df.head()

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned

In [5]:
df.columns

Index(['Patient_ID', 'Age', 'City', 'Surgery_Type', 'Operation_Duration_Min',
       'Length_of_Stay_Days', 'Admission_Type'],
      dtype='str')

In [6]:
df.shape

(10, 7)

In [7]:
# Display only Patient_ID, City, Surgery_Type, and Admission_Type.

df["Admission_Type"]

0      Planned
1    Emergency
2    Emergency
3      Planned
4      Planned
5    Emergency
6    Emergency
7      Planned
8      Planned
9      Planned
Name: Admission_Type, dtype: str

In [8]:
df["Surgery_Type"]

0     Cholecystectomy
1                CABG
2        Appendectomy
3       Hernia Repair
4    Knee Replacement
5                PTCA
6        Appendectomy
7     Cholecystectomy
8       Hernia Repair
9    Knee Replacement
Name: Surgery_Type, dtype: str

In [9]:

df["City"]

0     Hyderabad
1      Warangal
2     Hyderabad
3    Vijayawada
4     Hyderabad
5     Nizamabad
6     Hyderabad
7      Warangal
8     Hyderabad
9    Karimnagar
Name: City, dtype: str

In [10]:
df["Patient_ID"]

0    P101
1    P102
2    P103
3    P104
4    P105
5    P106
6    P107
7    P108
8    P109
9    P110
Name: Patient_ID, dtype: str

In [11]:
# Find all patients whose Admission_Type is "Emergency". Display the complete records.

In [12]:
df[df["Admission_Type"] == "Emergency"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency

In [13]:
# Find all surgeries where the operation duration is greater than 150 minutes.

In [14]:
df[df["Operation_Duration_Min"] > 150]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
1,P102,62,Warangal,CABG,240,7,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [15]:
# Find all Hyderabad patients and display Patient_ID, Age, Surgery_Type, and Admission_Type.

In [16]:
df[df["City"] == "Hyderabad"][["Patient_ID","Age","Surgery_Type","Admission_Type"]]

  Patient_ID  Age      Surgery_Type Admission_Type
0       P101   45   Cholecystectomy        Planned
2       P103   34      Appendectomy      Emergency
4       P105   41  Knee Replacement        Planned
6       P107   29      Appendectomy      Emergency
8       P109   47     Hernia Repair        Planned

In [17]:
# Calculate the average operation duration across all recorded surgeries.

In [18]:
df["Operation_Duration_Min"].mean()

np.float64(133.0)

In [19]:
# Find the highest operation duration recorded in the dataset. Return only the maximum duration value.

In [20]:
df["Operation_Duration_Min"].max()

np.int64(240)

In [21]:
# Find dynamically which patient had the longest operation and what type of surgery was performed. Display Patient_ID,
# Surgery_Type, and Operation_Duration_Min. Do not manually identify the patient.

In [22]:
df[(df["Operation_Duration_Min"] == df["Operation_Duration_Min"].max()) & df["Surgery_Type"]][["Patient_ID",
"Surgery_Type", "Operation_Duration_Min"]]

C:\Users\anadm\AppData\Local\Temp\ipykernel_27232\372455639.py:1: Pandas4Warning: 'and' operations between boolean dtype and str are deprecated and will raise in a future version. Explicitly cast the strings to a boolean dtype before operating instead.
  df[(df["Operation_Duration_Min"] == df["Operation_Duration_Min"].max()) & df["Surgery_Type"]][["Patient_ID",

  Patient_ID Surgery_Type  Operation_Duration_Min
1       P102         CABG                     240

In [23]:
# Find patients with operation duration > 100 minutes AND length of stay > 3 days. Display Patient_ID, Surgery_Type,
# Operation_Duration_Min, and Length_of_Stay_Days.

In [24]:
df[(df["Operation_Duration_Min"] > 100) & (df["Length_of_Stay_Days"] > 3)][["Patient_ID", "Surgery_Type","Operation_Duration_Min", "Length_of_Stay_Days"]]

  Patient_ID      Surgery_Type  Operation_Duration_Min  Length_of_Stay_Days
1       P102              CABG                     240                    7
4       P105  Knee Replacement                     180                    5
5       P106              PTCA                     150                    4
9       P110  Knee Replacement                     200                    6

In [25]:
# Find all Emergency cases where the operation took more than 100 minutes. Display Patient_ID, Surgery_Type,
# Operation_Duration_Min, and Admission_Type.

In [26]:
df[df["Operation_Duration_Min"] > 100][["Patient_ID", "Surgery_Type",
 "Operation_Duration_Min",  "Admission_Type"]]

  Patient_ID      Surgery_Type  Operation_Duration_Min Admission_Type
1       P102              CABG                     240      Emergency
3       P104     Hernia Repair                     110        Planned
4       P105  Knee Replacement                     180        Planned
5       P106              PTCA                     150      Emergency
8       P109     Hernia Repair                     120        Planned
9       P110  Knee Replacement                     200        Planned

In [27]:
# Management wants to identify patients who had a long operation AND stayed in the hospital for a long period.
#  Business
# rules: Operation duration > 100 minutes and Length of stay > 3 days. Return only Patient_ID and Surgery_Type. Write
# Pandas code that solves the requirement dynamically and continues to work if additional records are added.

In [28]:
df[(df["Operation_Duration_Min"] > 100) & (df["Length_of_Stay_Days"]) > 3][["Patient_ID","Surgery_Type"]]

Empty DataFrame
Columns: [Patient_ID, Surgery_Type]
Index: []

In [29]:
df.loc[0,"Patient_ID"]  #specific row and columns

'P101'

In [30]:
df.loc[:,["Patient_ID","Surgery_Type"]]   #for multiple columns

  Patient_ID      Surgery_Type
0       P101   Cholecystectomy
1       P102              CABG
2       P103      Appendectomy
3       P104     Hernia Repair
4       P105  Knee Replacement
5       P106              PTCA
6       P107      Appendectomy
7       P108   Cholecystectomy
8       P109     Hernia Repair
9       P110  Knee Replacement

loc with condition

iloc----> postion ke based par selection

In [31]:
df.iloc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [32]:
df.iloc[1]

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [33]:
df.iloc[0,0] #specific , rows and columns

'P101'

In [34]:
#first 3 columns
df.iloc[0:3]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency

In [35]:
#first three rows and 3 columns

df.iloc[0:3,0:3]

  Patient_ID  Age       City
0       P101   45  Hyderabad
1       P102   62   Warangal
2       P103   34  Hyderabad

loc vs iloc

#loc
label /condition based column name use 
df.loc[0,"city]
use for business filtering

#easy trick
loc--label
iloc--integer positions

In [36]:
df.iloc[0:3,0:2]

  Patient_ID  Age
0       P101   45
1       P102   62
2       P103   34

In [37]:
df.loc[:,["Patient_ID"]]

  Patient_ID
0       P101
1       P102
2       P103
3       P104
4       P105
5       P106
6       P107
7       P108
8       P109
9       P110

In [38]:
#idxmax() # interview point of view oriented

In [39]:
df["Operation_Duration_Min"].idxmax()

1

In [40]:
#manger ko required information chahiye Patient_ID, Surgery_type

In [41]:
df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [42]:
df.loc[df["Operation_Duration_Min"].idxmax()],["Patient_ID","Surgery_Type","Operation_Duration_Min"]

(Patient_ID                     P102
 Age                              62
 City                       Warangal
 Surgery_Type                   CABG
 Operation_Duration_Min          240
 Length_of_Stay_Days               7
 Admission_Type            Emergency
 Name: 1, dtype: object,
 ['Patient_ID', 'Surgery_Type', 'Operation_Duration_Min'])

In [43]:
df["Operation_Duration_Min"].max()

np.int64(240)

In [44]:
df["Operation_Duration_Min"].idxmax()

1

manager ko required information patient_id,

In [45]:
df.loc[df["Operation_Duration_Min"].idxmax(),["Patient_ID","Surgery_Type"]]

Patient_ID      P102
Surgery_Type    CABG
Name: 1, dtype: str

questions 
find the patient who had the longest day in the hospital
take only the  first 8 patient from this patients find the longest operatons

In [46]:
df.loc[df["Length_of_Stay_Days"].idxmax()]

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [47]:
df.iloc[:8,df["Operation_Duration_Min"].idxmax()]

0    45
1    62
2    34
3    55
4    41
5    68
6    29
7    52
Name: Age, dtype: int64